### PR TITLE
IMPORT FOREIGN SCHEMA support

### PR DESCRIPTION
**Pull request by josiah-co**
Hello, I hope your day is going well.

This adds support for `IMPORT FOREIGN SCHEMA`.

- [x] tests
- [x] >1600 column count handling
- [x] 63 character column prefix handling

I've been testing it in a local container by injecting this replacement fdw.py script into the container via `COPY`. From there, I run a templated query:
```
CREATE EXTENSION IF NOT EXISTS multicorn;
DROP SCHEMA IF EXISTS {new_schema} CASCADE;
DROP SERVER IF EXISTS {server_name} CASCADE;
CREATE SERVER {server_name} FOREIGN DATA WRAPPER multicorn
    OPTIONS (
        wrapper 'bigquery_fdw.fdw.ConstantForeignDataWrapper',
        fdw_dataset '{foreign_schema}',
        fetch_size '10000'
    );
CREATE SCHEMA {new_schema};
GRANT USAGE ON SCHEMA {new_schema} TO {self.user};
IMPORT FOREIGN SCHEMA {foreign_schema}
    FROM SERVER {server_name} INTO {new_schema};
```

After this, `select * from bq_schema.bq_table` works from inside Postgres, for any `new_schema` or table imported.

Please let me know if you're interested in tests. Thank you!

### CODE REVIEW

**Comment by gabfl** [comment]
@josiah-co I think it's a really interesting feature

> Please let me know if you're interested in tests. Thank you!
Thats would be great, yes

**Comment by josiah-co** [comment]
@gabfl Added some tests in a completely different style, can move them out into a different test class if you'd like.

**Comment by gabfl** [comment]
@josiah-co I apologize for not following up earlier. Are you still interested in contributing to this PR?

**Comment by josiah-co** [comment]
I don't currently have the allocated hours at work to spend on this. If you wanted to close, it wouldn't hurt my feelings.

Thank you for your time, and happy holidays!

**Comment by gabfl-confiant** [comment]
ok, closing for now and I will re-open if I have time to work on it myself

Thank you

**Comment by gabfl** [comment]
ok, closing for now and I will re-open if I have time to work on it myself

Thank you

**Pull request closed without merging**
